### ISSUE TITLE
Site not gumplete

### ISSUE THREAD

**Issue by lenoah-chacko** [nithinmanoj10/Plannr#3]
To aid you with completing this, please refer to this guide- https://bit.ly/3xI8TUr

**Comment by varghese1508** [comment]
Hey @lenoah-chacko, I understand and empathize with your issue. Indeed, it warrants immediate attention as well.

We would greatly appreciate it if you wielded the power of open source and undertook this responsibility yourself. [Refer to this tutorial for instructions on how to proceed.](https://www.youtube.com/watch?v=wpV-gGA4PSk&ab_channel=NicolYT)

Thank you for your valuable feedback and opinion, looking forward to your contribution!

**Comment by nithinmanoj10** [comment]
Thank you @lenoah-chacko . Without your help and guidance we wouldn't be able to gumplete this website on time. 
I would also like to thank my colleague @varghese1508 for immediately responding to the issues raised by the client.
Last but not the least, I would like to thank the Almighty, without Whom we wouldn't be here. We shall observe a moment of silence.




Stay tuned and do look out for our future projects [here](https://www.youtube.com/watch?v=k8xysDelDO4)
